mounts:
  - source: assets
    target: assets
  - source: hugo_stats.json
    target: assets/watching/hugo_stats.json
  - source: _huge
    target: assets/_huge

imports:
  - path: github.com/theNewDynamic/huge
